name: Pull request
on:
  workflow_dispatch:

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  artifacts:
    name: Artifacts
    uses: ./.github/workflows/artifacts.yml
