name: Main
on:
  workflow_dispatch:

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  prerelease:
    name: Prerelease
    uses: ./.github/workflows/prerelease.yml
    secrets: inherit